### ISSUE TITLE
Update usernames on Online Battle Card

### ISSUE THREAD

**Issue by idiglove** [idiglove/aintboard#193]
<img width="695" alt="image" src="https://user-images.githubusercontent.com/29911508/165673394-f99e4342-ecdc-45a2-bb0b-7582a6f32998.png">

Right now there are placeholders on each trophy awardee. 
* If the date is before the end date of the battle, show TBA.
* If the date is due or after, show the username or empty string if there's no winner

**Comment by halodong** [comment]
Hello, I came across this project at [https://goodfirstissues.com/](https://goodfirstissues.com/,) and found that the technology stack of this project and my own technology stack have a lot of overlap, so I thought, can you give me this issue to solve?

**Comment by idiglove** [comment]
Hi sure thing! I'll assign it to you
You can join the discord server as well for more specific questions and discussions

**Comment by halodong** [comment]
> Hi sure thing! I'll assign it to you You can join the discord server as well for more specific questions and discussions

ok thank you, i have joined the discord server
